services:
  mikrotik-backup:
    image: rclone/rclone:latest
    container_name: mikrotik-backup
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=America/Guatemala
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config/rclone
      - ./.ssh:/app/.ssh:ro
      - ./scripts/backup.sh:/app/backup.sh:ro
      - ./temp_backups:/backups
    entrypoint: /bin/sh
    command:
      - -c
      - |
        apk add --no-cache openssh-client tzdata && \
        echo "0 3 * * * sh /app/backup.sh >> /var/log/backup.log 2>&1" > /etc/crontabs/root && \
        exec crond -f -l 2
